tap "homebrew/bundle"

# Cross-platform make
brew "cmake"
# Secure runtime for JavaScript and TypeScript
brew "deno"
# Mac App Store command-line interface
brew "mas"
# Display directories as trees (with optional color/HTML output)
brew "tree"

# Simple application that will prevent iTunes or Apple Music from launching
cask "notunes"
# Wine wrapper built with SwiftUI
cask "whisky"
# # App to build and share containerised applications and microservices
# cask "docker"
# # Web browser
# cask "firefox"
# # Web browser
# cask "google-chrome"
# # Open-source code editor
# cask "visual-studio-code"
# # Video communication and virtual meeting platform
# cask "zoom"

# mas "AdGuard for Safari", id: 1440147259
# mas "Slack", id: 803453959
# mas "Telegram", id: 747648890
# mas "Xcode", id: 497799835
