#!/bin/bash

# ref:
# - https://github.com/sobolevn/dotfiles/blob/master/Brewfile
# - https://github.com/mathiasbynens/dotfiles/blob/main/brew.sh
# - https://github.com/volny/dotconfig/blob/master/Brewfile

. ../bash/helpers

is_command_installed_or_exit "xcode-select"

if ! is_command_installed "brew"; then
    echo "Brew is not installed. Installing Brew..."

    /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
else
    echo "Brew is already installed. Updating Brew..."

    brew update
fi

# Save Homebrew’s installed location
BREW_PREFIX=$(brew --prefix)

# Upgrade any already-installed formulae
brew upgrade

# Install all dependencies in the Brewfile
brew bundle --file ./Brewfile

# Remove outdated versions from the cellar
brew cleanup
